services:
  frontend-app:
    build: ./app/frontend
    volumes:
      - ./app/frontend:/workspace:cached
    tty: true

  db:
    image: mysql:8
    command:
      --collation-server=utf8mb4_0900_bin
      --transaction-isolation=READ-COMMITTED
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app
      MYSQL_USER: root1
      MYSQL_PASSWORD: password1
      TZ: Asia/Tokyo
    ports:
      - 53306:3306
