services:
  backend-app:
    container_name: backend-app
    build: ../
    image: fullstack_back
    volumes:
      - ../../..:/workspace:cached
    depends_on:
      db:
        condition: service_healthy
    command: sleep infinity

  db:
    container_name: db
    image: mysql:8
    command:
      --collation-server=utf8mb4_0900_bin
      --transaction-isolation=READ-COMMITTED
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app
      MYSQL_USER: root1
      MYSQL_PASSWORD: password1
      TZ: Asia/Tokyo
    ports:
      - 53306:3306
    volumes:
      - db-compose-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  db-compose-volume:
